//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GestionConsultationEntities : DbContext
    {
        public GestionConsultationEntities()
            : base("GestionConsultationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultation> Consultations { get; set; }
        public virtual DbSet<Local> Locals { get; set; }
        public virtual DbSet<MaisonMedicale> MaisonMedicales { get; set; }
        public virtual DbSet<Medecin> Medecins { get; set; }
        public virtual DbSet<MedecinSpecialite> MedecinSpecialites { get; set; }
        public virtual DbSet<MedecinSpecialiteMaisonMedicale> MedecinSpecialiteMaisonMedicales { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Presence> Presences { get; set; }
        public virtual DbSet<Specialite> Specialites { get; set; }
    
        public virtual int AddMaisonMedicale(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddMaisonMedicale", nameParameter);
        }
    
        public virtual int AddMaisonMedicaleForMedecin(Nullable<int> medecinSpecialite_ID, Nullable<int> maisonMedicale_ID, Nullable<int> minimalDuration, Nullable<bool> isActif)
        {
            var medecinSpecialite_IDParameter = medecinSpecialite_ID.HasValue ?
                new ObjectParameter("MedecinSpecialite_ID", medecinSpecialite_ID) :
                new ObjectParameter("MedecinSpecialite_ID", typeof(int));
    
            var maisonMedicale_IDParameter = maisonMedicale_ID.HasValue ?
                new ObjectParameter("MaisonMedicale_ID", maisonMedicale_ID) :
                new ObjectParameter("MaisonMedicale_ID", typeof(int));
    
            var minimalDurationParameter = minimalDuration.HasValue ?
                new ObjectParameter("MinimalDuration", minimalDuration) :
                new ObjectParameter("MinimalDuration", typeof(int));
    
            var isActifParameter = isActif.HasValue ?
                new ObjectParameter("IsActif", isActif) :
                new ObjectParameter("IsActif", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddMaisonMedicaleForMedecin", medecinSpecialite_IDParameter, maisonMedicale_IDParameter, minimalDurationParameter, isActifParameter);
        }
    
        public virtual ObjectResult<AddMedecin_Result> AddMedecin(string firstname, string lastname)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("Firstname", firstname) :
                new ObjectParameter("Firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("Lastname", lastname) :
                new ObjectParameter("Lastname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddMedecin_Result>("AddMedecin", firstnameParameter, lastnameParameter);
        }
    
        public virtual int AddPatient(string firstname, string lastname)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("Firstname", firstname) :
                new ObjectParameter("Firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("Lastname", lastname) :
                new ObjectParameter("Lastname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPatient", firstnameParameter, lastnameParameter);
        }
    
        public virtual int AddSpecialiteForMedecin(Nullable<int> specialite_ID, Nullable<int> medecin_ID)
        {
            var specialite_IDParameter = specialite_ID.HasValue ?
                new ObjectParameter("Specialite_ID", specialite_ID) :
                new ObjectParameter("Specialite_ID", typeof(int));
    
            var medecin_IDParameter = medecin_ID.HasValue ?
                new ObjectParameter("Medecin_ID", medecin_ID) :
                new ObjectParameter("Medecin_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddSpecialiteForMedecin", specialite_IDParameter, medecin_IDParameter);
        }
    
        public virtual int DeleteSpecialiteForMedecin(Nullable<int> medecinSpecialite_ID)
        {
            var medecinSpecialite_IDParameter = medecinSpecialite_ID.HasValue ?
                new ObjectParameter("MedecinSpecialite_ID", medecinSpecialite_ID) :
                new ObjectParameter("MedecinSpecialite_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteSpecialiteForMedecin", medecinSpecialite_IDParameter);
        }
    
        public virtual ObjectResult<GetAllMedecin_Result> GetAllMedecin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllMedecin_Result>("GetAllMedecin");
        }
    
        public virtual ObjectResult<GetAllSpecialite_Result> GetAllSpecialite()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllSpecialite_Result>("GetAllSpecialite");
        }
    
        public virtual ObjectResult<GetAllSpecialiteForMedecin_Result> GetAllSpecialiteForMedecin(Nullable<int> medecin_ID)
        {
            var medecin_IDParameter = medecin_ID.HasValue ?
                new ObjectParameter("Medecin_ID", medecin_ID) :
                new ObjectParameter("Medecin_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllSpecialiteForMedecin_Result>("GetAllSpecialiteForMedecin", medecin_IDParameter);
        }
    
        public virtual int UpdateMinimalDurationOfConsultation(Nullable<int> medecinSpecialiteMaisonMedicale_ID, Nullable<int> minimalDuration)
        {
            var medecinSpecialiteMaisonMedicale_IDParameter = medecinSpecialiteMaisonMedicale_ID.HasValue ?
                new ObjectParameter("MedecinSpecialiteMaisonMedicale_ID", medecinSpecialiteMaisonMedicale_ID) :
                new ObjectParameter("MedecinSpecialiteMaisonMedicale_ID", typeof(int));
    
            var minimalDurationParameter = minimalDuration.HasValue ?
                new ObjectParameter("MinimalDuration", minimalDuration) :
                new ObjectParameter("MinimalDuration", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMinimalDurationOfConsultation", medecinSpecialiteMaisonMedicale_IDParameter, minimalDurationParameter);
        }
    }
}
