//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedecinSpecialite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedecinSpecialite()
        {
            this.MedecinSpecialiteMaisonMedicales = new HashSet<MedecinSpecialiteMaisonMedicale>();
        }
    
        public int MedecinSpecialite_ID { get; set; }
        public int Medecin_ID { get; set; }
        public int Specialite_ID { get; set; }
    
        public virtual Medecin Medecin { get; set; }
        public virtual Specialite Specialite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinSpecialiteMaisonMedicale> MedecinSpecialiteMaisonMedicales { get; set; }
    }
}
