//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        public int Presence_ID { get; set; }
        public int Medecin_ID { get; set; }
        public int MaisonMedicale_ID { get; set; }
        public System.DateTime Starting { get; set; }
        public System.DateTime Ending { get; set; }
    
        public virtual MaisonMedicale MaisonMedicale { get; set; }
        public virtual Medecin Medecin { get; set; }
    }
}
